backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "static/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "projects"
    label: "Projects"
    folder: "projects"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/project.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "thumbnailSrc", widget: "image"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}